version: '3'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '9000:9000'
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '9001:9001'
      - '9002:9002'
      - '9003:9003'
